USE ROLE SECURITYADMIN; 
CREATE OR REPLACE ROLE DEV_ARF_GCC_DATA_ENGINEER;
GRANT ROLE DEV_ARF_GCC_DATA_ENGINEER TO ROLE SYSADMIN;
CREATE OR REPLACE ROLE DEV_ARF_SC_DATA_ENGINEER;
GRANT ROLE DEV_ARF_SC_DATA_ENGINEER TO ROLE SYSADMIN; 
GRANT ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL TO ROLE DEV_ARF_SC_DATA_ENGINEER;
GRANT ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL TO ROLE DEV_ARF_SC_DATA_ENGINEER;

GRANT ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_GCC_REPORTING_SFULL TO ROLE DEV_ARF_GCC_DATA_ENGINEER;
GRANT DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO TO ROLE DEV_ARF_GCC_DATA_ENGINEER;

SHOW WAREHOUSES;

GRANT USAGE ON WAREHOUSE TASTY_BYTES_DBT_WH TO ROLE DEV_ARF_GCC_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE TASTY_BYTES_DBT_WH TO ROLE DEV_ARF_SC_DATA_ENGINEER;

USE ROLE SYSADMIN;
--landing DB
CREATE DATABASE GM_SF_DBT_PROJECT_DEMO_LANDING_DB;
CREATE SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW;

CREATE OR REPLACE DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
CREATE OR REPLACE DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRW;
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;


GRANT DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRW;
GRANT DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRW TO  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT   ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL TO  ROLE SYSADMIN;


//grant SELECT access to the READ role. 
GRANT USAGE ON SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT SELECT ON ALL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT SELECT ON ALL VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT SELECT ON ALL STREAMS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT MONITOR ON ALL TASKS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;


--READ FUTURE
GRANT SELECT ON FUTURE TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRO;


//grant access to the READ WRITE role, RW role inherits rights from READ role. This does not require the same grants made previously
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON ALL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRW;
GRANT INSERT, UPDATE, DELETE, REFERENCES ON ALL EXTERNAL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO  DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRW;
GRANT WRITE ON ALL STAGES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRW;
GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRW;

 --WRITE FUTURE
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON FUTURE TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRW;
GRANT INSERT, UPDATE, DELETE, REFERENCES ON FUTURE EXTERNAL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRW;
GRANT READ,WRITE ON FUTURE STAGES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRW;
GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW_SRW;


//grant access to SFULl role
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON ALL EXTERNAL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON ALL MATERIALIZED VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON ALL STAGES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON ALL TASKS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL; 
GRANT CREATE  DBT PROJECT  ON SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL; 
 

//OWNERSHIP FUTURE
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE EXTERNAL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_RAW_SFULL; 



GRANT USAGE ON DBT PROJECT   "GM_SF_DBT_PROJECT_DEMO_LANDING_DB"."STANDARDISED"."GM_SNF_DBT_DEMO" TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;

SHOW GRANTS TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL TO ROLE DEV_ARF_SC_DATA_ENGINEER;

USE ROLE DEV_ARF_SC_DATA_ENGINEER;;

create or replace   view GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED.raw_pos_truck
  
   as (
    SELECT *
FROM GM_SF_DBT_PROJECT_DEMO_LANDING_DB.RAW.TRUCK
  );

