--- standardised schema

CREATE OR REPLACE SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED;

CREATE OR REPLACE DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
CREATE OR REPLACE DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRW;
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;

GRANT DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRW;
GRANT DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRW TO  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT   ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL TO  ROLE SYSADMIN;

//grant SELECT access to the READ role. 
GRANT USAGE ON SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT SELECT ON ALL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT SELECT ON ALL VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT SELECT ON ALL STREAMS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT MONITOR ON ALL TASKS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;


--READ FUTURE
GRANT SELECT ON FUTURE TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRO;


//grant access to the READ WRITE role, RW role inherits rights from READ role. This does not require the same grants made previously
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON ALL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRW;
GRANT INSERT, UPDATE, DELETE, REFERENCES ON ALL EXTERNAL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO  DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRW;
GRANT WRITE ON ALL STAGES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRW;
GRANT MONITOR,OPERATE ON ALL TASKS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRW;

 --WRITE FUTURE
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES ON FUTURE TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRW;
GRANT INSERT, UPDATE, DELETE, REFERENCES ON FUTURE EXTERNAL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRW;
GRANT READ,WRITE ON FUTURE STAGES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRW;
GRANT MONITOR,OPERATE ON FUTURE TASKS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO DATABASE  ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED_SRW;

 
//grant access to SFULl role
GRANT OWNERSHIP ON ALL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE  GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT CREATE TABLE   ON SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE  GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON ALL EXTERNAL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT CREATE VIEW  ON SCHEMA  GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE   GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON ALL MATERIALIZED VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON ALL STREAMS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON ALL STAGES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON ALL FILE FORMATS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON ALL TASKS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON ALL SEQUENCES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON ALL PROCEDURES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL; 
GRANT CREATE  DBT PROJECT  ON SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL; 
 

//OWNERSHIP FUTURE
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON FUTURE EXTERNAL TABLES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON FUTURE MATERIALIZED VIEWS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON FUTURE FILE FORMATS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON FUTURE SEQUENCES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL;
GRANT OWNERSHIP ON FUTURE PROCEDURES IN SCHEMA GM_SF_DBT_PROJECT_DEMO_LANDING_DB.STANDARDISED TO ROLE GM_SF_DBT_PROJECT_DEMO_LANDING_DB_STANDARDISED_SFULL; 
